package com.openfinova.banking.gl.api.entity;

/**
 * Source of a GL transaction, used to determine approval requirements
 * and processing rules.
 *
 * System-generated and batch transactions typically auto-post without approval,
 * while manual entries require maker-checker approval workflow.
 */
public enum GLTransactionSource {

    /**
     * Manual journal entry created by an accountant.
     * REQUIRES APPROVAL - subject to maker-checker workflow.
     */
    MANUAL_ENTRY,

    /**
     * Correction or adjustment to fix previous errors.
     * REQUIRES APPROVAL - high-risk operation requiring review.
     */
    CORRECTION,

    /**
     * Reclassification between accounts.
     * REQUIRES APPROVAL - requires review to ensure proper classification.
     */
    RECLASSIFICATION,

    /**
     * System-generated transaction (period closing, revaluation, etc.).
     * AUTO-POSTED - no approval needed, generated by automated processes.
     */
    SYSTEM_GENERATED,

    /**
     * Batch import from subledger or external system.
     * AUTO-POSTED - pre-validated in source system, aggregated for GL.
     */
    BATCH_IMPORT,

    /**
     * Real-time feed from operational systems (core banking interface).
     * AUTO-POSTED - operational transactions already processed, GL summarization.
     */
    INTERFACE_FEED,

    /**
     * Automated calculation (interest accrual, fee assessment, etc.).
     * AUTO-POSTED - rule-based automated process.
     */
    AUTO_CALCULATED;

    /**
     * Check if this transaction source requires maker-checker approval.
     *
     * @return true if approval workflow is required
     */
    public boolean requiresApproval() {
        return this == MANUAL_ENTRY || this == CORRECTION || this == RECLASSIFICATION;
    }

    /**
     * Check if this is a system-generated transaction (auto-posted).
     *
     * @return true if transaction is automatically generated
     */
    public boolean isSystemGenerated() {
        return this == SYSTEM_GENERATED || this == BATCH_IMPORT || this == INTERFACE_FEED || this == AUTO_CALCULATED;
    }

    /**
     * Check if this source represents manual human intervention.
     *
     * @return true if transaction was manually created by a user
     */
    public boolean isManual() {
        return this == MANUAL_ENTRY || this == CORRECTION || this == RECLASSIFICATION;
    }
}
