<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.openfinova</groupId>
		<artifactId>openfinova-banking-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>general-ledger</artifactId>
	<packaging>pom</packaging>
	<name>general-ledger</name>
	<description>General Ledger modules for Banking Application</description>

	<modules>
		<module>general-ledger-api</module>
		<module>general-ledger-service</module>
	</modules>

</project>
